### PR TITLE
Update k8schain's k8s dependency to 0.21.0

### PR DESCRIPTION
**Pull request by imjasonh**
https://github.com/google/go-containerregistry/issues/997#issuecomment-827181676

I edited `go.mod` to bump the versions, then ran `go mod download` as recommended by `go build ./...`, then `go mod tidy`.

### CODE REVIEW

**Comment by ImJasonH** [comment]
It looks like the nondeterminism is still present in v1.21.0 :( 

- https://github.com/kubernetes/kubernetes/blob/v1.21.0/staging/src/k8s.io/component-base/version/base.go#L59
- https://github.com/kubernetes/kubernetes/blob/v1.21.0/staging/src/k8s.io/client-go/pkg/version/base.go#L59

**Comment by jonjohnsonjr** [comment]
Do we need to bump `github.com/vdemeester/k8s-pkg-credentialprovider`?

cc @vdemeester

**Comment by vdemeester** [comment]
@jonjohnsonjr we probably should indeed

**Comment by imjasonh** [comment]
> @jonjohnsonjr we probably should indeed

https://github.com/vdemeester/k8s-pkg-credentialprovider/pull/10

**Comment by imjasonh** [comment]
vdemeester/k8s-pkg-credentialprovider#10 is updated

**Comment by jonjohnsonjr** [comment]
Why do we need all the replace directives?

**Comment by vdemeester** [comment]
> Why do we need all the replace directives?

Yeah agreed, I think we should try to get rid of the `replace` as much as possible.

**Comment by vdemeester** [comment]
I think I need to fix something of k8s-pkg-credentialprovider though

**Comment by vdemeester** [comment]
> I think I need to fix something of k8s-pkg-credentialprovider though

It is done, @imjasonh updated to 1.21.0-1 👼🏼

**Review by jonjohnsonjr — APPROVED** [review]

**Pull request merged**
