### PR TITLE
Use vdemeester/k8s-pkg-credentialprovider temporarly 🌬

### PR DESCRIPTION
**Pull request by vdemeester**
This removes the dependency to `k8s.io/kubernetes` and use a "frozen
in time" version of this package.

This is temporary in the sense, that once
https://github.com/kubernetes/enhancements/pull/1406 is done, this
will not be needed anymore and we should switch back to using it
instead.

/cc @jonjohnsonjr 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vdemeester** [comment]
The second commit updates the `vendor` folder that didn't seem up-to-date :sweat_smile: 
Not sure if we should keep it or removing it :angel:

**Comment by jonjohnsonjr** [comment]
@vdemeester I think this may have broken our image publishing stuff... `go get github.com/google/ko/cmd/ko` fails with:

> Step #0: build github.com/google/ko/cmd/ko: cannot load k8s.io/api/admissionregistration/v1alpha1: module k8s.io/api@latest found (v0.17.1), but does not contain package k8s.io/api/admissionregistration/v1alpha1

We might just need to update `ko`?

**Comment by vdemeester** [comment]
oh right, I guees so :thinking: I can try to take a look tomorrow :angel:

**Comment by jonjohnsonjr** [comment]
https://github.com/google/ko/pull/119 might fix it

**Pull request merged**
