### PR TITLE
Return better error when pulling schema 1

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
See https://github.com/GoogleContainerTools/kaniko/issues/509

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
Possibly, this is too much text:

```
$ crane pull ruby:2.1.2 old.tar
2019/01/10 06:11:34 Pulling index.docker.io/library/ruby:2.1.2
2019/01/10 06:11:34 No matching credentials were found, falling back on anonymous
2019/01/10 06:11:35 writing image "old.tar": missing config digest, image is probably schema 1; manifest body:
{
   "name": "library/ruby",
   "tag": "2.1.2",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:ffca5e0e07182135a7e794da7c3b733b22d70a01f4c8b106dcee41069f08c7e8"
      },
      {
         "blobSum": "sha256:5bd64402bda1070a98e644af5ec77bcd561a94572fe3329289e689b30af3fbb0"
      },
      {
         "blobSum": "sha256:7bfcfa20e94cd2332b8068da1620f3d452e4379e180840e16fafb928aef6fc98"
      },
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:34695db0bdf0de0b73f98c925c5f75e333a1c4a3ec53fc30fcad8c9efcfaff99"
      },
      {
         "blobSum": "sha256:935b2cc382fb9a06e363805a85760c2eeb0e8ae6fa8e459080fda9344ae99200"
      },
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "blobSum": "sha256:ca4ef1007b9613207d6915e2336c333f9d44fd04305525fe35a5f8964b542e92"
      },
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      }
   ],
   "history": [
      {
         "v1Compatibility": "{\"id\":\"227510c3fed610bc1fd5da5513c9caf647b18a688b0126fbfda38b73082636a2\",\"parent\":\"3f0a5e11e9092d612cb03d898c8818d99d809be88df3fbab78c624be6fe8830d\",\"created\":\"2014-09-15T20:34:57.073534469Z\",\"container\":\"9e1a09379f7fa0c3883f2f789d1481fe4f8268a2a33f6cba69f355430bcede58\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) CMD [irb]\"],\"Image\":\"3f0a5e11e9092d612cb03d898c8818d99d809be88df3fbab78c624be6fe8830d\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.2.0\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"irb\"],\"Image\":\"3f0a5e11e9092d612cb03d898c8818d99d809be88df3fbab78c624be6fe8830d\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":0}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"227510c3fed610bc1fd5da5513c9caf647b18a688b0126fbfda38b73082636a2\",\"parent\":\"3f0a5e11e9092d612cb03d898c8818d99d809be88df3fbab78c624be6fe8830d\",\"created\":\"2014-09-15T20:34:57.073534469Z\",\"container\":\"9e1a09379f7fa0c3883f2f789d1481fe4f8268a2a33f6cba69f355430bcede58\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) CMD [irb]\"],\"Image\":\"3f0a5e11e9092d612cb03d898c8818d99d809be88df3fbab78c624be6fe8830d\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.2.0\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"irb\"],\"Image\":\"3f0a5e11e9092d612cb03d898c8818d99d809be88df3fbab78c624be6fe8830d\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":0}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"3f0a5e11e9092d612cb03d898c8818d99d809be88df3fbab78c624be6fe8830d\",\"parent\":\"82e1f245c8b89b0f440f8d60ffec38bf0e587d17cb85f38b4380f8a765e691ac\",\"created\":\"2014-09-15T20:34:56.719999722Z\",\"container\":\"b10750d835e4aa289fa431ce102482bd4bca62150a07f866d9b9b278a3d54e80\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"gem install bundler\"],\"Image\":\"82e1f245c8b89b0f440f8d60ffec38bf0e587d17cb85f38b4380f8a765e691ac\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.2.0\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/bash\"],\"Image\":\"82e1f245c8b89b0f440f8d60ffec38bf0e587d17cb85f38b4380f8a765e691ac\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":3902682}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"82e1f245c8b89b0f440f8d60ffec38bf0e587d17cb85f38b4380f8a765e691ac\",\"parent\":\"ea8073371d8e2911adeb4bca6b689688c5e9c7cca98f043f043fd4c57e2b3833\",\"created\":\"2014-09-15T20:34:52.934217705Z\",\"container\":\"cb69a5a6a3e499516d0d28240e2eb6880d55865c33893270fe32cb6b2fdb67a6\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"echo 'gem: --no-rdoc --no-ri' \\u003e\\u003e /.gemrc\"],\"Image\":\"ea8073371d8e2911adeb4bca6b689688c5e9c7cca98f043f043fd4c57e2b3833\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.2.0\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/bash\"],\"Image\":\"ea8073371d8e2911adeb4bca6b689688c5e9c7cca98f043f043fd4c57e2b3833\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":23}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"ea8073371d8e2911adeb4bca6b689688c5e9c7cca98f043f043fd4c57e2b3833\",\"parent\":\"1b631079e7c114f699ab6c5f1b3a94eed65fa212db3d96051b5b7671a8f3a72a\",\"created\":\"2014-09-15T20:34:50.436894017Z\",\"container\":\"439b24997c0696d99ad09f664ef3121d3cf1789dc989b10e2dbc591f461b1cf8\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"apt-get update  \\u0026\\u0026 apt-get install -y bison curl ruby procps  \\u0026\\u0026 rm -rf /var/lib/apt/lists/*  \\u0026\\u0026 mkdir -p /usr/src/ruby  \\u0026\\u0026 curl -SL \\\"http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR/ruby-$RUBY_VERSION.tar.bz2\\\"   | tar -xjC /usr/src/ruby --strip-components=1  \\u0026\\u0026 cd /usr/src/ruby  \\u0026\\u0026 autoconf  \\u0026\\u0026 ./configure --disable-install-doc  \\u0026\\u0026 make -j\\\"$(nproc)\\\"  \\u0026\\u0026 apt-get purge -y --auto-remove bison ruby procps  \\u0026\\u0026 make install  \\u0026\\u0026 rm -r /usr/src/ruby\"],\"Image\":\"1b631079e7c114f699ab6c5f1b3a94eed65fa212db3d96051b5b7671a8f3a72a\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.2.0\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/bash\"],\"Image\":\"1b631079e7c114f699ab6c5f1b3a94eed65fa212db3d96051b5b7671a8f3a72a\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":99679817}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"1b631079e7c114f699ab6c5f1b3a94eed65fa212db3d96051b5b7671a8f3a72a\",\"parent\":\"0ed331685b4fc094b0a9a89dbecc185584f02ef013d4f02513e83e8926ebac20\",\"created\":\"2014-09-02T17:38:53.035523381Z\",\"container\":\"f8bc61e9729ea2a031a3e448d7e605a68b6628d6fb64567feab31605dd835ea4\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) ENV RUBY_VERSION=2.1.2\"],\"Image\":\"0ed331685b4fc094b0a9a89dbecc185584f02ef013d4f02513e83e8926ebac20\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.1.2\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\",\"RUBY_VERSION=2.1.2\"],\"Cmd\":[\"/bin/bash\"],\"Image\":\"0ed331685b4fc094b0a9a89dbecc185584f02ef013d4f02513e83e8926ebac20\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":0}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"0ed331685b4fc094b0a9a89dbecc185584f02ef013d4f02513e83e8926ebac20\",\"parent\":\"4f442c2069ca3084766776d07da759b2032248e9be4a0df63150950f011581c5\",\"created\":\"2014-09-02T17:38:52.481945217Z\",\"container\":\"8122ed366a666c593fd6eba324fc79a8b390ee5393f40e58b27ab563b4642385\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) ENV RUBY_MAJOR=2.1\"],\"Image\":\"4f442c2069ca3084766776d07da759b2032248e9be4a0df63150950f011581c5\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.1.2\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"RUBY_MAJOR=2.1\"],\"Cmd\":[\"/bin/bash\"],\"Image\":\"4f442c2069ca3084766776d07da759b2032248e9be4a0df63150950f011581c5\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":0}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"4f442c2069ca3084766776d07da759b2032248e9be4a0df63150950f011581c5\",\"parent\":\"b31651d7665036bcf58a0b6b0d7aca173daff87b003ec50621cb0fde8d68864f\",\"created\":\"2014-08-31T02:42:10.11784599Z\",\"container\":\"b7b9ab94dcccae2b9a87c15c676d28b7e9383c76cbe3ec2133a75de6082636bb\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"apt-get update \\u0026\\u0026 apt-get install -y   bzr   cvs   git   mercurial   subversion  \\u0026\\u0026 rm -rf /var/lib/apt/lists/*\"],\"Image\":\"b31651d7665036bcf58a0b6b0d7aca173daff87b003ec50621cb0fde8d68864f\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.1.2\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/bash\"],\"Image\":\"b31651d7665036bcf58a0b6b0d7aca173daff87b003ec50621cb0fde8d68864f\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":116390126}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"b31651d7665036bcf58a0b6b0d7aca173daff87b003ec50621cb0fde8d68864f\",\"parent\":\"431dac4e3917b2ead2adca847cb76bd7222b8a889fcb22d38da7f8b0441ec9bd\",\"created\":\"2014-08-31T02:41:14.355416176Z\",\"container\":\"b7dbc18806d1b0684ed051b1f05a0176fa7a95de14de6bdf51e7edfe2123ad52\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"apt-get update \\u0026\\u0026 apt-get install -y   autoconf   build-essential   imagemagick   libbz2-dev   libcurl4-openssl-dev   libevent-dev   libffi-dev   libglib2.0-dev   libjpeg-dev   libmagickcore-dev   libmagickwand-dev   libmysqlclient-dev   libncurses-dev   libpq-dev   libpq-dev   libreadline-dev   libsqlite3-dev   libssl-dev   libxml2-dev   libxslt-dev   libyaml-dev   zlib1g-dev  \\u0026\\u0026 rm -rf /var/lib/apt/lists/*\"],\"Image\":\"431dac4e3917b2ead2adca847cb76bd7222b8a889fcb22d38da7f8b0441ec9bd\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.1.2\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/bash\"],\"Image\":\"431dac4e3917b2ead2adca847cb76bd7222b8a889fcb22d38da7f8b0441ec9bd\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":580375206}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"431dac4e3917b2ead2adca847cb76bd7222b8a889fcb22d38da7f8b0441ec9bd\",\"parent\":\"a70fb0647e6ef2b9056a3866188c133281c4dcf895d926b57c546c81b9f11e6d\",\"created\":\"2014-08-12T03:54:31.191289594Z\",\"container\":\"088f93b9e688a898c7f1fc7aa1231c6926278e58b2c588c417a37dcdfffbe0b2\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) CMD [/bin/bash]\"],\"Image\":\"a70fb0647e6ef2b9056a3866188c133281c4dcf895d926b57c546c81b9f11e6d\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.1.2\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/bash\"],\"Image\":\"a70fb0647e6ef2b9056a3866188c133281c4dcf895d926b57c546c81b9f11e6d\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":0}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"a70fb0647e6ef2b9056a3866188c133281c4dcf895d926b57c546c81b9f11e6d\",\"parent\":\"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158\",\"created\":\"2014-08-12T03:54:28.819903765Z\",\"container\":\"d304c8ed47ea05538d1585e2bf1c43f4210a8e8b59c368955d1be230f29df0a6\",\"container_config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) ADD file:29e52cbeed164d50b33063694cdb46aa56f7410c17235c4ff8a30183741d21eb in /\"],\"Image\":\"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"docker_version\":\"1.1.2\",\"config\":{\"Hostname\":\"d304c8ed47ea\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"HOME=/\",\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":null,\"Image\":\"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":[],\"Labels\":null},\"architecture\":\"amd64\",\"os\":\"linux\",\"Size\":90075045}\n"
      },
      {
         "v1Compatibility": "{\"id\":\"511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158\",\"comment\":\"Imported from -\",\"created\":\"2013-06-13T14:03:50.821769-07:00\",\"container_config\":{\"Hostname\":\"\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"PortSpecs\":null,\"ExposedPorts\":null,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":null,\"Image\":\"\",\"Volumes\":null,\"VolumeDriver\":\"\",\"WorkingDir\":\"\",\"Entrypoint\":null,\"NetworkDisabled\":false,\"MacAddress\":\"\",\"OnBuild\":null,\"Labels\":null},\"docker_version\":\"0.4.0\",\"architecture\":\"x86_64\",\"Size\":0}\n"
      }
   ],
   "schemaVersion": 1,
   "signatures": [
      {
         "header": {
            "jwk": {
               "crv": "P-256",
               "kid": "U4PI:24HT:WFM2:T4SB:CXRE:JHAN:U56Z:ZYCS:YCFA:CJZ2:CBUF:UQTR",
               "kty": "EC",
               "x": "TOe2e7eSvqmlsegH2P9iFRh5qvqR3lcCyVL0qKzIb2I",
               "y": "J8PUaKBft6cdMBkR8HHNpSSLS3AHXYeh-pr3d9YdQBs"
            },
            "alg": "ES256"
         },
         "signature": "Adxo_HcARYOfNBD-ltkSUczQ_ptSIgABoKDaH0berdlW8eI-xZQoeEQ2Vq4Btxq9yL2Jxz577t-AgjKDcxZ2mQ",
         "protected": "eyJmb3JtYXRMZW5ndGgiOjIxOTk0LCJmb3JtYXRUYWlsIjoiQ24wIiwidGltZSI6IjIwMTktMDEtMTBUMDY6MTE6MzlaIn0"
      }
   ]
}
```

**Comment by jonjohnsonjr** [comment]
Closed for https://github.com/google/go-containerregistry/issues/377 instead.

**Comment by glyn** [comment]
@jonjohnsonjr Should this PR be resurrected unless and until https://github.com/google/go-containerregistry/issues/377 is implemented?

**Comment by jonjohnsonjr** [comment]
Yeah I think I have a better way of handling this than we do in this PR by actually checking the returned mediaType instead of trying to parse it. I'll send a simpler one.

**Comment by glyn** [comment]
@jonjohnsonjr Thanks. Raised https://github.com/google/go-containerregistry/issues/411 so this doesn't get forgotten.

**Pull request closed without merging**
