### PR TITLE
match.Platforms and match.Digests

### PR DESCRIPTION
**Pull request by deitch**
Option to:

* `match.Platforms([]v1.Platform)` for any one of them.
* `match.Digest(v1.Hash)`
* `match.Digests([]v1.Hash)` for any one of them.

Also tests, of course.

### CODE REVIEW

**Comment by deitch** [comment]
Updated to include `match.Digest` and `match.Digests`

**Comment by deitch** [comment]
Review, please @jonjohnsonjr ?

**Comment by jonjohnsonjr** [comment]
I'm kinda -1 on having both `match.Foo` and `match.Foos` for everything...

Option 1:

```go
func Foo(foo Foo) Matcher
func Foos(foos []Foo) Matcher
```

Option 2:

```go
// Clients have to use match.Foos([]Foo{foo})
func Foos(foos []Foo) Matcher
```

Option 3:

```go
// Works with match.Foos(foo) and match.Foos(foo, bar)
func Foos(foos ...Foo) Matcher
```

Option 4:

```go
// Works with match.Foo(foo) and match.Foo(foo, bar)
func Foo(foos ...Foo) Matcher
```

WDYT? Order of preference for me is probably 4, 3, 1, 2.

We already have `match.MediaTypes` for 2, but this has been merged for such a short window that I'd be fine making a breaking change for that to make it consistent.

**Comment by deitch** [comment]
Oh, yeah, I like 4. Variadic is so nice and easy. The question is, should it be named:

```go
func Foo(foo Foo...) Matcher
```

or

```go
func Foos(foo Foo...) Matcher
```

I think the second, since it can match multiple?

**Comment by jonjohnsonjr** [comment]
They're about equivalent to me, so whichever you prefer.

**Comment by deitch** [comment]
OK, updated @jonjohnsonjr ; take a look. I did `MediaTypes` too, as you suggested.

**Review by jonjohnsonjr — APPROVED** [review]

**Pull request merged**
