### PR TITLE
expose the layer media type

### PR DESCRIPTION
**Pull request by dprotaso**
Signed-off-by: Dave Protasowski <dprotaso@gmail.com>

### CODE REVIEW

**Comment by ImJasonH** [comment]
Can you motivate this change a bit with some context? Is there some feature that's blocked by not having this?

**Comment by dprotaso** [comment]
Folks seem to pushing new 'archive' types to registries

ie. 
https://github.com/google/crfs#introducing-stargz
https://github.com/containerd/containerd/issues/2267#issuecomment-455406681

Hence why it'd be nice if the `v1.Layer` were to expose the original media type of the layer.

**Comment by jonjohnsonjr** [comment]
I'm not completely convinced... I had some similar changes at one point when I was playing with the OCI image layout stuff, but then I didn't actually use it in any implementation. I think the `Layer` interface is kind of strange because of `Compressed`/`Uncompressed`. Perhaps what those really should be are something like `Distributable` and `Tarball` to distinguish between passing through the registry vs consuming as a filesystem.

**Comment by dprotaso** [comment]
I think it’s less about the original of the stream but the content aka
media type. ie. docker layers are a tar stream

tar most likely will be supplemented in the future by some other thing so
knowing the media type would be valuable

the above examples demonstrate that

**Pull request merged**
