### PR TITLE
Created: `string` -> `time.Time`

### LINKED ISSUE #35: Docker can't parse our created times
Not sure where exactly the issue is, but Docker can't parse an empty creation time. Trying to docker load a saved tarball gives:

```shell
parsing time """" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "2006"
```

### PR DESCRIPTION
**Pull request by dekkagaijin**
Fix #35 

Signed-off-by: Jake Sanders <jsand@google.com>

### CODE REVIEW

**Comment by dlorenc** [comment]
Nice. We should add this to the list of things to validate in #30

**Comment by dekkagaijin** [comment]
@dlorenc If we want to start taking dependencies on Docker's types, sure. They just use json.(Un)Marshal, so the only really interesting thing is the serialization roundtrips.

**Comment by dlorenc** [comment]
Ah, it looks like this is the parsing code they use: https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/api/types/time/timestamp.go

I guess whatever we write has to be formatted in one of these four formats: https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/api/types/time/timestamp.go#L13

Up to you if you think it's worth testing.

**Comment by dekkagaijin** [comment]
@dlorenc I'd say that that'd be a fairly superfluous reason to start going down the rabbit hole of vendoring  Docker. Might be better served with an e2e test in Travis. Luckily, these types are relatively static.

**Comment by dekkagaijin** [comment]
FYI those 4 are extra, it also handles the standard RFC 3339- compliant formats:
https://github.com/moby/moby/blob/3a633a712c8bbb863fe7e57ec132dd87a9c4eff7/api/types/time/timestamp.go#L31

**Comment by dlorenc** [comment]
Yeah definitely agree about not wanting to vendor docker just for this... I think it might be useful in #30 or somewhere else though. There are a bunch of things that can make docker unhappy even though something looks like an image, so having a utility to validate something that implements an Image interface would be really useful.

**Pull request merged**
