### PR TITLE
Bump github.com/containerd/stargz-snapshotter/estargz to v0.4.0

### PR DESCRIPTION
**Pull request by ktock**
https://github.com/containerd/stargz-snapshotter/issues/244

github.com/containerd/stargz-snapshotter/estargz v0.4.0 is released.

### CODE REVIEW

**Review by ImJasonH — APPROVED** [review]

**Comment by ktock** [comment]
Sorry, just bumped to v0.4.1. PTAL.

**Comment by ImJasonH** [comment]
Thanks! Can you also run hack/update-deps.sh to vendor in the new code?

**Comment by ktock** [comment]
No code change happen since v0.0.0-20201223015020-a9a0c2d64694, actually (and I've run hack/update-deps.sh),
but we started to tag `estargz` module so the purpose of this commit is to use the released tag in go.mod instead of (unreleased) commit hash for better maintainability.

**Comment by ImJasonH** [comment]
Oh okay, thanks!

**Comment by jonjohnsonjr** [comment]
Thanks!

**Pull request merged**
