### PR TITLE
Fix error when calculating tarball size of manifest

### PR DESCRIPTION
**Pull request by tydra-wang**
Manifest is marshalled repeatedly.

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
cc @deitch can you take a look?

**Review by deitch — APPROVED** [review]
It makes sense to me. I cannot understand how it worked before, unless I simply don't understand it now.

**Review by jonjohnsonjr — APPROVED** [review]
Thanks!

**Comment by tydra-wang** [comment]
> It makes sense to me. I cannot understand how it worked before, unless I simply don't understand it now.

The `size` is only used to calculate the progress.
And the tarball padding makes error happens occasionally.

**Pull request merged**
