### PR TITLE
Add godoc badge

### PR DESCRIPTION
**Pull request by zchee**
Add godoc badge and format badge links like https://github.com/google/gops.

### CODE REVIEW

**Comment by dekkagaijin** [comment]
dude, welcome

**Comment by dekkagaijin** [comment]
ようこそgo-containerregistryへ
よろしくお願いします

**Comment by zchee** [comment]
lol, but very good Japanese!! :D
I’m interesting this project.

**Comment by dekkagaijin** [comment]
Thanks :D

It's a golang port of https://github.com/google/containerregistry, and already have a bunch of internal use cases for the library, but I suspect a bunch of external demand could surface as well. Not everyone wants to take a dependency on `dockerd` in order to build, push, or pull images :)

**Pull request merged**
