### PR TITLE
Bump ecr-login to v0.6.0

### PR DESCRIPTION
**Pull request by imjasonh**
https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.6.0

### CODE REVIEW

**Comment by imjasonh** [comment]
@mattmoor ECR tests failing with:

```
OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint
```

And also some mysterious Go modules failure for `go install ./cmd/krane` I can't seem to reproduce locally. 🤔

**Comment by dprotaso** [comment]
This is a big feature 🎉 

> Feature - Added support to assume roles via EC2 instance metadata.

**Review by mattmoor — APPROVED** [review]

**Comment by mattmoor** [comment]
@imjasonh ah, let me regenerate it.  I hate the thumbprint shit.

**Pull request merged**
