### PR TITLE
Feat(crane) support push tarball contains more than one image

### PR DESCRIPTION
**Pull request by dashjay**
[Issue here: Support crane push tarBall contains more than one image?](https://github.com/google/go-containerregistry/issues/1109)
This is my first contribution to the open source repo. Bear with me 🥺 .

- [x] add command mpush for pushing tarball contains more than one image
- [x] merge command mpush and command push

.....Please don't hesitate to ask any questions that may exist

### CODE REVIEW

**Comment by dashjay** [comment]
@googlebot I signed it!

**Comment by dashjay** [comment]
@googlebot I fixed it.

**Comment by dashjay** [comment]
I want to know why this function [remote.MultiWrite](https://github.com/google/go-containerregistry/blob/de8aff85c9090d37ed6fe436d696f3a820e5c767/pkg/v1/remote/multi_write.go#L44) says that all refs must share the same repository. I can not understand it... so I define a func named WriteMulti

**Comment by dashjay** [comment]
`crane push TARBALL image:tag` can push a tarball contain one image to specific tag. but now it can just only change the registry. like this:
```
[registry]/[repository]:[tag] -> [new-registry]/[repository]:[tag]
```

you can not change the repository and tag...

**Comment by jonjohnsonjr** [comment]
Hey sorry I missed this PR. The idea in general is good. I don't think we need to add a new method to `remote` -- we could just iterate over the map in `crane` and push each individually. We can optimize that later.

Want to start with just a PR to add the `MultiImage` function to the `tarball` package? I have some feedback but don't want to have to churn too much until we're happy with that function.

**Comment by dashjay** [comment]
@jonjohnsonjr I didn't mean any offense, I will do like what you said(remove the new method in remote and just iter the map ~), thank you for review again.
Two weeks ago, I closed it because I found that, there is something wrong with the auth. I can not WriteMulti to registry with Self-signed SSL. I read all code but can not resolve it.

**Pull request closed without merging**
