### PR TITLE
Allow setting Content-Type in crane edit manifest

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
This uses the --media-type flag.

### CODE REVIEW

**Comment by tianon** [comment]
Can this new flag default to the `mediaType` in my edited document? :pleading_face:

(I want to be able to convert docs from Docker media types to OCI media types :bow:)

**Comment by tianon** [comment]
I suppose I should report back that I successfully tested this PR for converting an image from Docker media types to OCI media types and all went well. :smile:

**Review by imjasonh — APPROVED** [review]

**Comment by imjasonh** [comment]
> I suppose I should report back that I successfully tested this PR for converting an image from Docker media types to OCI media types and all went well. :smile:

Would a command just to OCIfy a docker image be helpful? That's something we've found a need for in the past and then punted on.

**Comment by tianon** [comment]
Hmmm, as a flag to `crane cp` maybe?  I don't think I'd personally use it, though, since it's just as easy to munge the 2-3 media types myself and I don't actually do this kind of munging very often (and hopefully even less over time!)

I ran into this while testing something _else_ the first time, and it was only the second time that I was trying to OCI-ify an existing image that I decided to really bug Jon about it in earnest since it seemed like an easy win for the overall ergonomics of `crane edit` matching my expectations of how it was about to work. :joy:

**Comment by tianon** [comment]
Mostly just to make Jon cringe, I'd be happy to write a `jq` one-liner for the docs so you can suggest users do `crane manifest ... | jq '...' | crane edit manifest ...` if that's helpful :smile:

**Comment by jonjohnsonjr** [comment]
> Would a command just to OCIfy a docker image be helpful? That's something we've found a need for in the past and then punted on.

I'm 99% sure there's a PR to do this somewhere.

**Comment by tianon** [comment]
> > Would a command just to OCIfy a docker image be helpful? That's something we've found a need for in the past and then punted on.
> 
> I'm 99% sure there's a PR to do this somewhere.

Looks like that's #1293 (also relevant is #1245)

**Pull request merged**
