### PR TITLE
Bump deps, fix issues

### PR DESCRIPTION
**Pull request by imjasonh**
Fixes https://github.com/google/go-containerregistry/issues/1361

### CODE REVIEW

**Comment by imjasonh** [comment]
`misspell` doesn't ignore `vendor/`... 😒

**Comment by imjasonh** [comment]
Bump deps failed again for the same reason: https://github.com/google/go-containerregistry/actions/runs/2020584456

**Comment by imjasonh** [comment]
Updated this to use `-compat=1.17` for all the modules.

**Comment by imjasonh** [comment]
Fixes https://github.com/google/go-containerregistry/issues/1361

**Review by jonjohnsonjr — APPROVED** [review]

**Pull request merged**
