### PR TITLE
Fork k8s.io/kubernetes/pkg/credentialprovider

### LINKED ISSUE #496: Please stop importing k8s.io/kuberneretes
Kubernetes only wants people to import things like k8s.io/api k8s.io/client-go, not k8s.io/kubernetes directly. This is why a bunch of k8s.io/kubernetes deps are [pinned to version v0.0.0](https://github.com/kubernetes/kubernetes/blob/39724859b524e345881eb8ef458f0d5a2f25bd9a/go.mod#L148-L173) to discourage its use.

See https://github.com/kubernetes/kubernetes/issues/81878 

Example usage: https://github.com/google/go-containerregistry/blob/31e00cede111067bae48bfc2cbfc522b0b36207f/pkg/authn/k8schain/k8schain.go#L25

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
* Bump kubernetes 1.11.3 -> 1.15.3
* Fork the credentialprovider stuff that we need into pkg/internal/k8s

Fixes #496 

This isn't quite ready to merge -- the k8schain unit test now takes 20s because the AWS provider tries to talk to the metadata server with several retries. Not sure how to fix that or if it actually will affect real life uses of k8schain.

cc @bobcatfish @nkubala

### CODE REVIEW

**Comment by nkubala** [comment]
FWIW, I tried pinning to this commit in skaffold and running daily `mod` commands, and everything seems to work (as much as it can, we'll need knative to make similar changes).

I know this is probably less work....but did you consider trying to push for k8s to make these changes? :see_no_evil:

**Comment by jonjohnsonjr** [comment]
They're targeting 1.17 and it's slipped twice already -- I'm not sure how soon that will be fixed upstream.

**Comment by afrittoli** [comment]
> They're targeting 1.17 and it's slipped twice already -- I'm not sure how soon that will be fixed upstream.

Do you have a link to the work planned on k8s side?

**Comment by jonjohnsonjr** [comment]
@afrittoli the only context I have is the GitHub milestone for https://github.com/kubernetes/kubernetes/issues/74379

**Comment by jonjohnsonjr** [comment]
There's some movement on https://github.com/kubernetes/kubernetes/issues/82396 so I'm going to close this.

**Pull request closed without merging**
