### PR TITLE
Fix Azure Container Registry authentication

### LINKED ISSUE #1255: Issues with Azure Container Registry authentication
Hi!

Thank you so much for the great work you are doing here. :1st_place_medal: 

I've been troubleshooting an issue with `cosign` where Azure Container Registry authentication doesn't work and found two issues which I hope I've understood correctly.

The first issue was related to the helper being used and I've created a separate issue and PR for that: https://github.com/chrismellard/docker-credential-acr-env/issues/3

Before the fix for the helper, I would see the following in `cosign`:
```shell
./cosign verify --k8s-keychain --key azurekms://sigstore.vault.azure.net/sigstore myregistry.azurecr.io/mycontainer:dev
ERRO[0000] Error parsing the serverURL                   error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=myregistry.azurecr.io/mycontainer
Error: GET https://myregistry.azurecr.io/oauth2/token?scope=repository%3Amycontainer%3Apull&service=myregistry.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.
main.go:46: error during command execution: GET https://myregistry.azurecr.io/oauth2/token?scope=repository%3Amycontainer%3Apull&service=myregistry.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.
```

After using the patched helper, I get the following:
```shell
./cosign verify --k8s-keychain --key azurekms://sigstore.vault.azure.net/sigstore myregistry.azurecr.io/mycontainer:dev
ERRO[0000] Error parsing the serverURL                   error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=myregistry.azurecr.io/mycontainer
Error: GET https://myregistry.azurecr.io/oauth2/token?scope=repository%3Amycontainer%3Apull&service=myregistry.azurecr.io: UNAUTHORIZED: aad access token with sp failed invalid request
main.go:46: error during command execution: GET https://myregistry.azurecr.io/oauth2/token?scope=repository%3Amycontainer%3Apull&service=myregistry.azurecr.io: UNAUTHORIZED: aad access token with sp failed invalid request
```

After additional trobuleshooting of the issue, I figured out the following: 
The helper wrapper being used for Azure Container Registry in `go-containerregistry` is returning a username and password, where the username is `<token>`.

If we read the comment in code, it says that OAuth will be used if username is set to `<token>` - but this only applies if we have an `IdentityToken` instead of a `Password` which is what the helper wrapper returns.

We can clearly see when using ACR locally it's using IdentityToken: (~/.docker/config.json)
```json
{
        "auths": {
                "myregistry.azurecr.io": {
                        "auth": "MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwOg==",
                        "identitytoken": "eyI...In0"
                }
        }
}
```

I'm not sure what the best solution here is, I've tested with using my own helper wrapper that returns IdentityToken instead of password and it works as expected.

Reference for the IdentityToken check: https://github.com/google/go-containerregistry/blob/86ab60664adc985dec1a8ab30af5cddf3c610db3/pkg/v1/remote/transport/bearer.go#L138-L142

Reference for the helper wrapper not setting IdentityToken: https://github.com/google/go-containerregistry/blob/86ab60664adc985dec1a8ab30af5cddf3c610db3/pkg/authn/keychain.go#L161

I'm not completely sure what you would prefer here, but I'll start off by adding a new wrapper and using it with Azure Container Registry.

Feel free to point out any and all errors I've done and things I've missed here. Spent a few more hours than I thought I would have an may have missed something really obvious.

Reference to the cosign issue: https://github.com/sigstore/cosign/issues/1350

### PR DESCRIPTION
**Pull request by simongottschlag**
Fixes #1255

I'm not sure if this is the best or preferred way of handling this, another way may be to add a check to `NewKeychainFromHelper()` that checks if the username is `<token>` and adds `IdentityToken` to the `AuthConfig{}`.

Any and all feedback is welcome and if you see that I've missed something obvious and that's why I've done this, please point it out and I'll fix the issue where it's located.

### CODE REVIEW

**Comment by simongottschlag** [comment]
I will try to fix the corporate CLA on Monday.

**Comment by imjasonh** [comment]
Thanks so much for your investigation into why this was broken, and for your thorough description, and for your PR. If we're ever in the same place and you'd like a beer, it's on me. 🍻 

I think I'd be okay changing `NewKeychainFromHelper` to check if `username == "<token>"` and pass the password as the auth config's `IdentityToken`, if that's how I'm supposed to interpret this section of [the docs for `docker login`](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers):

> If the secret being stored is an identity token, the Username should be set to `<token>`.

(...and if that's practically how cred helpers in the wild work today)

If that's the case then we'd only need to change `NewKeychainFromHelper` and not also have to change `cosign` and downstream callers to use the `IdentityTokenHelper` variant.

What do you think?

cc @jonjohnsonjr

**Comment by simongottschlag** [comment]
@imjasonh hi! 😊

No problem at all! Just fun 🎉 Beer sounds nice 🍻 

I agree with you and will update the PR. 😊👍

**Comment by imjasonh** [comment]
Hey, so I think if we change [this line](https://github.com/google/go-containerregistry/blob/main/pkg/authn/keychain.go#L157) to pass `r.RegistryStr()` instead of `r.String()` (which includes the repo component) then it should also work around https://github.com/chrismellard/docker-credential-acr-env/issues/3

https://github.com/google/go-containerregistry/blob/main/pkg/authn/keychain.go#L157

I think all parts of this bug can be fixed inside our own code 🎉

**Comment by simongottschlag** [comment]
@imjasonh nice catch! Do you want it in a separate PR or is it OK in this one?

**Comment by imjasonh** [comment]
I'm fine to include it in this one.

**Comment by simongottschlag** [comment]
@imjasonh added! I've validated that it's working in my environment (only Azure though).

**Review by imjasonh — APPROVED** [review]

**Comment by simongottschlag** [comment]
We should have signed the corporate CLA from our side today, but I think it needs to be counter signed by Google and we're waiting for that right now.

**Comment by imjasonh** [comment]
> We should have signed the corporate CLA from our side today, but I think it needs to be counter signed by Google and we're waiting for that right now. I can't see anything about it when logged in at least. I'll check back tomorrow and see if there's any updates.

If it's okay, I've opened https://github.com/google/go-containerregistry/pull/1265 which adds on this PR and includes unit tests. And since I'm already cleared for the CLA, we can merge it without waiting for Google. I'd like to get this included in cosign soon so they can cut a v1.5.1 with this fix for Azure users such as yourself.

(If you'd prefer to wait for the Google CLA, please let me know and I'll close mine, I don't mean to step on any toes)

Thanks again for your excellent work, and I look forward to working with you again more in the future! 👍

**Comment by simongottschlag** [comment]
Go for it! 🎉 Just close this one when you've merged yours 😊

**Pull request closed without merging**
