### PR TITLE
Add support for arm and arm64

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
Fixes https://github.com/google/go-containerregistry/issues/850

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
Seems to work?
```
$ goreleaser --snapshot --skip-publish --rm-dist
   • releasing...     
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • releasing v0.1.4, commit fd3fec5d0f09702accc262b49eabf3f0e3d2f116
      • pipe skipped              error=disabled during snapshot mode
   • parsing tag      
   • running before hooks
   • setting defaults 
      • snapshotting     
      • github/gitlab/gitea releases
      • project name     
      • building binaries
      • creating source archive
      • archives         
      • linux packages   
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • docker images    
      • artifactory      
      • blobs            
      • homebrew tap formula
      • scoop manifests  
      • milestones       
   • snapshotting     
   • checking ./dist  
   • writing effective config file
      • writing                   config=dist/config.yaml
   • generating changelog
      • pipe skipped              error=not available for snapshots
   • building binaries
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/crane_windows_amd64/crane.exe
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/crane_linux_386/crane
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/crane_linux_amd64/crane
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/crane_linux_arm_6/crane
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/crane_linux_arm64/crane
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/crane_darwin_amd64/crane
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/gcrane_windows_amd64/gcrane.exe
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/gcrane_linux_arm_6/gcrane
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/gcrane_linux_amd64/gcrane
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/gcrane_linux_386/gcrane
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/gcrane_linux_arm64/gcrane
      • building                  binary=/home/jonjohnson/go/src/github.com/google/go-containerregistry/dist/gcrane_darwin_amd64/gcrane
   • archives         
      • creating                  archive=dist/go-containerregistry_Darwin_x86_64.tar.gz
      • creating                  archive=dist/go-containerregistry_Linux_x86_64.tar.gz
      • creating                  archive=dist/go-containerregistry_Linux_arm.tar.gz
      • creating                  archive=dist/go-containerregistry_Linux_i386.tar.gz
      • creating                  archive=dist/go-containerregistry_Linux_arm64.tar.gz
      • creating                  archive=dist/go-containerregistry_Windows_x86_64.tar.gz
   • creating source archive
      • pipe skipped              error=source pipe is disabled
   • linux packages   
   • snapcraft packages
   • calculating checksums
      • checksumming              file=go-containerregistry_Windows_x86_64.tar.gz
      • checksumming              file=go-containerregistry_Linux_x86_64.tar.gz
      • checksumming              file=go-containerregistry_Darwin_x86_64.tar.gz
      • checksumming              file=go-containerregistry_Linux_arm.tar.gz
      • checksumming              file=go-containerregistry_Linux_arm64.tar.gz
      • checksumming              file=go-containerregistry_Linux_i386.tar.gz
   • signing artifacts
   • docker images    
      • pipe skipped              error=docker section is not configured
   • publishing       
      • blobs            
         • pipe skipped              error=blobs section is not configured
      • http upload      
         • pipe skipped              error=uploads section is not configured
      • custom publisher 
         • pipe skipped              error=publishers section is not configured
      • artifactory      
         • pipe skipped              error=artifactory section is not configured
      • docker images    
         • pipe skipped              error=publishing is disabled
      • docker manifests 
         • pipe skipped              error=publishing is disabled
      • snapcraft packages
         • pipe skipped              error=publishing is disabled
      • github/gitlab/gitea releases
         • pipe skipped              error=publishing is disabled
      • homebrew tap formula
      • scoop manifests  
         • pipe skipped              error=publishing is disabled
      • milestones       
         • pipe skipped              error=publishing is disabled
   • release succeeded after 118.84s
```

**Review by mattmoor — APPROVED** [review]

**Comment by jonjohnsonjr** [comment]
image

Finally... let's see if anything breaks.

**Comment by jonjohnsonjr** [comment]
The google auth tests are broken on arm for some reason, so I've disabled them with `+build !arm64` for now.

I pruned the matrix down to just use go1.15 and `GO111MODULE=on` for everything except for amd64 tests, which will hopefully be less wasteful.

@ImJasonH added a test for `MultiWrite` that generated a truly monumental amount of logspam that slowed down the travis UI, so I fixed that as well.

```
=== RUN   TestMultiWrite_Deep
--- PASS: TestMultiWrite_Deep (38.07s)
```

That is still actually really slow... I'm surprised by it, but looking at the test it makes some sense:

idx[0] = 2 images
idx[1] = 2 images + idx[0] = 4 images
idx[2] = 2 images + idx[0] + idx[1] = 8 images
idx[3] = 2 images + idx[0] + idx[1] + idx[2] =  16 images
...
idx[10] = 2048 images ?

I'm still a bit surprised that we'd spend 38 seconds in that. In theory we'd calculate the digest just once for each layer. It looks like we don't memoize the digest for `random.Image` or `random.Index`... maybe we should? I'm guessing we spend most of that time just hashing stuff but I haven't actually measured.

**Comment by jonjohnsonjr** [comment]
So far everything but windows has passed so this looks pretty good.

**Comment by jonjohnsonjr** [comment]
🎉

**Pull request merged**
