### PR TITLE
remote/transport: Make bearer transport go-routine-safe

### PR DESCRIPTION
**Pull request by 2opremio**
Make the bearer transport safe for use by multiple go-routines.

I found the following race conditions in my application, when using the transport in a client making multiple concurrent requests.

<details>
  <summary>Data race backtraces</summary>

```
==================
WARNING: DATA RACE
Read at 0x00c00014c248 by goroutine 18:
  github.com/google/go-containerregistry/pkg/v1/remote/transport.(*bearerTransport).RoundTrip()
      /Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/bearer.go:163 +0x1fc
  github.com/google/go-containerregistry/pkg/v1/remote/transport.(*Wrapper).RoundTrip()
      /Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/transport.go:108 +0x4c
  net/http.send()
      /opt/local/lib/go/src/net/http/client.go:260 +0x6cc
  net/http.(*Client).send()
      /opt/local/lib/go/src/net/http/client.go:181 +0x100
  net/http.(*Client).do()
      /opt/local/lib/go/src/net/http/client.go:724 +0xc3c
  net/http.(*Client).Do()
      /opt/local/lib/go/src/net/http/client.go:590 +0x1cc
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.Proxy.getResponse()
      /Users/fons/docker-registry-proxy/internal/proxy/main.go:124 +0x1c4
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.Proxy.ServeHTTP()
      /Users/fons/docker-registry-proxy/internal/proxy/main.go:178 +0x714
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.(*Proxy).ServeHTTP()
      <autogenerated>:1 +0x84
  net/http.serverHandler.ServeHTTP()
      /opt/local/lib/go/src/net/http/server.go:2938 +0x298
  net/http.(*conn).serve()
      /opt/local/lib/go/src/net/http/server.go:2009 +0x8ec
  net/http.(*Server).Serve.func3()
      /opt/local/lib/go/src/net/http/server.go:3086 +0x4c

Previous write at 0x00c00014c248 by goroutine 25:
  github.com/google/go-containerregistry/pkg/v1/remote/transport.(*bearerTransport).RoundTrip()
      /Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/bearer.go:174 +0x3d8
  github.com/google/go-containerregistry/pkg/v1/remote/transport.(*Wrapper).RoundTrip()
      /Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/transport.go:108 +0x4c
  net/http.send()
      /opt/local/lib/go/src/net/http/client.go:260 +0x6cc
  net/http.(*Client).send()
      /opt/local/lib/go/src/net/http/client.go:181 +0x100
  net/http.(*Client).do()
      /opt/local/lib/go/src/net/http/client.go:724 +0xc3c
  net/http.(*Client).Do()
      /opt/local/lib/go/src/net/http/client.go:590 +0x1cc
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.Proxy.getResponse()
      /Users/fons/docker-registry-proxy/internal/proxy/main.go:124 +0x1c4
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.Proxy.ServeHTTP()
      /Users/fons/docker-registry-proxy/internal/proxy/main.go:178 +0x714
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.(*Proxy).ServeHTTP()
      <autogenerated>:1 +0x84
  net/http.serverHandler.ServeHTTP()
      /opt/local/lib/go/src/net/http/server.go:2938 +0x298
  net/http.(*conn).serve()
      /opt/local/lib/go/src/net/http/server.go:2009 +0x8ec
  net/http.(*Server).Serve.func3()
      /opt/local/lib/go/src/net/http/server.go:3086 +0x4c

Goroutine 18 (running) created at:
  net/http.(*Server).Serve()
      /opt/local/lib/go/src/net/http/server.go:3086 +0x5f4
  net/http.(*Server).ListenAndServe()
      /opt/local/lib/go/src/net/http/server.go:2985 +0xb0
  main.main.func3()
      /Users/fons/docker-registry-proxy/main.go:127 +0x2c

Goroutine 25 (running) created at:
  net/http.(*Server).Serve()
      /opt/local/lib/go/src/net/http/server.go:3086 +0x5f4
  net/http.(*Server).ListenAndServe()
      /opt/local/lib/go/src/net/http/server.go:2985 +0xb0
  main.main.func3()
      /Users/fons/docker-registry-proxy/main.go:127 +0x2c
==================
==================
WARNING: DATA RACE
Read at 0x00c00039a1c0 by goroutine 18:
  github.com/google/go-containerregistry/pkg/v1/remote/transport.stringSet()
      /Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/bearer.go:127 +0x4f4
  github.com/google/go-containerregistry/pkg/v1/remote/transport.(*bearerTransport).RoundTrip()
      /Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/bearer.go:163 +0x1f0
  github.com/google/go-containerregistry/pkg/v1/remote/transport.(*Wrapper).RoundTrip()
      /Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/transport.go:108 +0x4c
  net/http.send()
      /opt/local/lib/go/src/net/http/client.go:260 +0x6cc
  net/http.(*Client).send()
      /opt/local/lib/go/src/net/http/client.go:181 +0x100
  net/http.(*Client).do()
      /opt/local/lib/go/src/net/http/client.go:724 +0xc3c
  net/http.(*Client).Do()
      /opt/local/lib/go/src/net/http/client.go:590 +0x1cc
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.Proxy.getResponse()
      /Users/fons/docker-registry-proxy/internal/proxy/main.go:124 +0x1c4
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.Proxy.ServeHTTP()
      /Users/fons/docker-registry-proxy/internal/proxy/main.go:178 +0x714
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.(*Proxy).ServeHTTP()
      <autogenerated>:1 +0x84
  net/http.serverHandler.ServeHTTP()
      /opt/local/lib/go/src/net/http/server.go:2938 +0x298
  net/http.(*conn).serve()
      /opt/local/lib/go/src/net/http/server.go:2009 +0x8ec
  net/http.(*Server).Serve.func3()
      /opt/local/lib/go/src/net/http/server.go:3086 +0x4c

Previous write at 0x00c00039a1c0 by goroutine 25:
  runtime.slicecopy()
      /opt/local/lib/go/src/runtime/slice.go:310 +0x0
  github.com/google/go-containerregistry/pkg/v1/remote/transport.(*bearerTransport).RoundTrip()
      /Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/bearer.go:173 +0x3d0
  github.com/google/go-containerregistry/pkg/v1/remote/transport.(*Wrapper).RoundTrip()
      /Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/transport.go:108 +0x4c
  net/http.send()
      /opt/local/lib/go/src/net/http/client.go:260 +0x6cc
  net/http.(*Client).send()
      /opt/local/lib/go/src/net/http/client.go:181 +0x100
  net/http.(*Client).do()
      /opt/local/lib/go/src/net/http/client.go:724 +0xc3c
  net/http.(*Client).Do()
      /opt/local/lib/go/src/net/http/client.go:590 +0x1cc
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.Proxy.getResponse()
      /Users/fons/docker-registry-proxy/internal/proxy/main.go:124 +0x1c4
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.Proxy.ServeHTTP()
      /Users/fons/docker-registry-proxy/internal/proxy/main.go:178 +0x714
  dev.azure.com/cur8/TheRigg/_git/docker-registry-proxy/internal/proxy.(*Proxy).ServeHTTP()
      <autogenerated>:1 +0x84
  net/http.serverHandler.ServeHTTP()
      /opt/local/lib/go/src/net/http/server.go:2938 +0x298
  net/http.(*conn).serve()
      /opt/local/lib/go/src/net/http/server.go:2009 +0x8ec
  net/http.(*Server).Serve.func3()
      /opt/local/lib/go/src/net/http/server.go:3086 +0x4c

Goroutine 18 (running) created at:
  net/http.(*Server).Serve()
      /opt/local/lib/go/src/net/http/server.go:3086 +0x5f4
  net/http.(*Server).ListenAndServe()
      /opt/local/lib/go/src/net/http/server.go:2985 +0xb0
  main.main.func3()
      /Users/fons/docker-registry-proxy/main.go:127 +0x2c

Goroutine 25 (running) created at:
  net/http.(*Server).Serve()
      /opt/local/lib/go/src/net/http/server.go:3086 +0x5f4
  net/http.(*Server).ListenAndServe()
      /opt/local/lib/go/src/net/http/server.go:2985 +0xb0
  main.main.func3()
      /Users/fons/docker-registry-proxy/main.go:127 +0x2c
==================
```

</details>

A simplified application could be:

```go
package main

import (
	"net/http"
	
	"github.com/google/go-containerregistry/pkg/authn"
	"github.com/google/go-containerregistry/pkg/name"
	"github.com/google/go-containerregistry/pkg/v1/remote/transport"
)

func newAuthenticatingClient(host, user, password string) (*http.Client, error) {
	registry, err := name.NewRegistry(host)
	if err != nil {
		return nil, err
	}
	basicAuth := &authn.Basic{
		Username: user,
		Password: password,
	}
	tr, err := transport.New(registry, basicAuth, http.DefaultTransport, nil)
	if err != nil {
	  return nil, err
	}
	return &http.Client{Transport: tr}
}

func main() {
	client, err := newAuthenticatingClient("foo", "bar", "buzz")
	if err != nil {
		panic(err)
	}
	// make a lot of concurrent requests with client
}

```

### CODE REVIEW

**Comment by dmitris** [comment]
@2opremio - could you rebase the branch of this PR on the current trunk to pick up the latest changes, please?

**Comment by 2opremio** [comment]
@dmitris done!

**Comment by dmitris** [comment]
> It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

any chance you could do the CLA, @2opremio? Want to see your change in the main repo rather than having to apply it as a patch in CI 😄

**Comment by 2opremio** [comment]
I did! It should be approved, isn't it?

**Comment by dmitris** [comment]
@jonjohnsonjr - is this ready to merge or what do we need to move this ahead?  Could you please review it? 🙏 Thanks!

**Comment by 2opremio** [comment]
@dmitris can we please get this merged?

**Comment by dmitris** [comment]
> @dmitris can we please get this merged?

@2opremio I would love to but I'm not a repo owner or admin, don't have the rights to do this.

**Review by jonjohnsonjr — APPROVED** [review]

**Comment by dmitris** [comment]
thanks @jonjohnsonjr - could you also cut a new release (v0.20.3), please? /cc  @imjasonh

**Pull request merged**
