### PR TITLE
[Automated] Update actions

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
```shell
# meta: knative/.github
# main: google/go-containerregistry
cp $(find "${GITHUB_WORKSPACE}/meta/workflow-templates" -type f -name '*.yaml') \
  "${GITHUB_WORKSPACE}/main/.github/workflows/"
```
/cc @jonjohnsonjr @ImJasonH
/assign @jonjohnsonjr @ImJasonH

### CODE REVIEW

**Comment by mattmoor** [comment]
I think there's a test in here that only works on GCP 😞 

cc @ImJasonH @jonjohnsonjr

**Comment by mattmoor** [comment]
Once this lands, we should send a PR like: https://github.com/google/ko/pull/197 to enable some more of the checks these pulled in.

**Comment by ImJasonH** [comment]
This fails some unit tests, which seemingly depend on GCR/Google specifically: https://github.com/google/go-containerregistry/pull/773/checks?check_run_id=1226113237

**Comment by mattmoor** [comment]
switching bots

**Pull request closed without merging**
