### PR TITLE
Drop v1util now that 0.3 is cut

### PR DESCRIPTION
**Pull request by mattmoor**
Fixes: https://github.com/google/go-containerregistry/issues/873

### CODE REVIEW

**Comment by jonjohnsonjr** [comment]
I wish there was a way to notify dependents...

@jromero https://github.com/buildpacks/pack/blob/b94eca823bf12d50900ef21851aadfcfc53d1f80/testhelpers/tar_assertions.go#L136

@cppforlife https://github.com/vmware-tanzu/carvel-kbld/blob/4ac6f68865c23f87a6710d16f674933190d35858/pkg/kbld/imagedesc/described_layer.go#L12-L13

@debugmiller https://github.com/ForAllSecure/rootfs_builder/blob/adbe259b64bfe8e9186d9a1c6be7f7d7fc5eb036/rootfs/extract.go#L182

@achasveachas https://github.com/cloudfoundry/hydrator/blob/919ca7133daa42bf65b99c0af5f67ccac0691ae4/layermodifier/layermodifier.go#L92

**Comment by mattmoor** [comment]
Most of those folks are VMware, so I'll post to a few internal slack channels.

**Review by ImJasonH — APPROVED** [review]

**Comment by jromero** [comment]
Thanks @jonjohnsonjr. 

Rerouting to @dfreilich :)

**Comment by dfreilich** [comment]
Thanks! We'll get notified automatically when dependabot picks up the new dependency, and it isn't successful, but we'll try to polish it off before then.

**Review by jonjohnsonjr — APPROVED** [review]

**Comment by mattmoor** [comment]
Going to merge this, if folks are broken they can pin to the 0.3 release.

**Pull request merged**
